export const products = [
  {id: '1233', name: "Potion #16", price: 12.59, description: "awdwuiefgWIUERFG   IUWERTFGV   WIUYEFV", categories: ["aaaa", "bbbbb", "ccccc"], stock: 34, archived: false},
  {id: '7454', name: "Potion #16", price: 12.59, description: "awdwuiefgWIUERFG   IUWERTFGV   WIUYEFV", categories: ["aaaa", "bbbbb", "ccccc"], stock: 34, archived: false},
  {id: '1745745233', name: "Potion #16", price: 12.59, description: "awdwuiefgWIUERFG   IUWERTFGV   WIUYEFV", categories: ["aaaa", "bbbbb", "ccccc"], stock: 34, archived: true},
  {id: '12374574573', name: "Potion #16", price: 12.59, description: "awdwuiefgWIUERFG   IUWERTFGV   WIUYEFV", categories: ["aaaa", "bbbbb", "ccccc"], stock: 34, archived: false},
  {id: '8076', name: "Potion #16", price: 12.59, description: "awdwuiefgWIUERFG   IUWERTFGV   WIUYEFV", categories: ["aaaa", "bbbbb", "ccccc"], stock: 34, archived: false},
  {id: '67', name: "Potion #16", price: 12.59, description: "awdwuiefgWIUERFG   IUWERTFGV   WIUYEFV", categories: ["aaaa", "bbbbb", "ccccc"], stock: 34, archived: false},
  {id: '126733', name: "Potion #16", price: 12.59, description: "awdwuiefgWIUERFG   IUWERTFGV   WIUYEFV", categories: ["aaaa", "bbbbb", "ccccc"], stock: 34, archived: false},
  {id: '987689', name: "Potion #16", price: 12.59, description: "awdwuiefgWIUERFG   IUWERTFGV   WIUYEFV", categories: ["aaaa", "bbbbb", "ccccc"], stock: 34, archived: false},
  {id: '678967896', name: "Potion #16", price: 12.59, description: "awdwuiefgWIUERFG   IUWERTFGV   WIUYEFV", categories: ["aaaa", "bbbbb", "ccccc"],  stock: 34, archived: false},
  {id: '1269679633', name: "Potion #16", price: 12.59, description: "awdwuiefgWIUERFG   IUWERTFGV   WIUYEFV", categories: ["aaaa", "bbbbb", "ccccc"],  stock: 34, archived: false},
  {id: '123957683', name: "Potion #16", price: 12.59, description: "awdwuiefgWIUERFG   IUWERTFGV   WIUYEFV", categories: ["aaaa", "bbbbb", "ccccc"], stock: 34, archived: false},
  {id: '15860233', name: "Potion #16", price: 12.59, description: "awdwuiefgWIUERFG   IUWERTFGV   WIUYEFV", categories: ["aaaa", "bbbbb", "ccccc"], stock: 34, archived: false},
  {id: '12368076805983', name: "Potion #16", price: 12.59, description: "awdwuiefgWIUERFG   IUWERTFGV   WIUYEFV", categories: ["aaaa", "bbbbb", "ccccc"],stock: 34, archived: false},
  {id: '125679633', name: "Potion #16", price: 12.59, description: "awdwuiefgWIUERFG   IUWERTFGV   WIUYEFV", categories: ["aaaa", "bbbbb", "ccccc"], stock: 34, archived: false},
  {id: '127956975633', name: "Potion #16", price: 12.59, description: "awdwuiefgWIUERFG   IUWERTFGV   WIUYEFV", categories: ["aaaa", "bbbbb", "ccccc"], stock: 34, archived: true},
  {id: '12096809678067033', name: "Potion #16", price: 12.59, description: "awdwuiefgWIUERFG   IUWERTFGV   WIUYEFV", categories: ["aaaa", "bbbbb", "ccccc"],  stock: 34, archived: false},
  {id: '12809567806578033', name: "Potion #16", price: 12.59, description: "awdwuiefgWIUERFG   IUWERTFGV   WIUYEFV", categories: ["aaaa", "bbbbb", "ccccc"], stock: 34, archived: false},
  {id: '1237805673', name: "Potion #16", price: 12.59, description: "awdwuiefgWIUERFG   IUWERTFGV   WIUYEFV", categories: ["aaaa", "bbbbb", "ccccc"],  stock: 34, archived: false},
  {id: '1290467846733', name: "Potion #16", price: 12.59, description: "awdwuiefgWIUERFG   IUWERTFGV   WIUYEFV", categories: ["aaaa", "bbbbb", "ccccc"], stock: 34, archived: false},
  {id: '1678095678233', name: "Potion #16", price: 12.59, description: "awdwuiefgWIUERFG   IUWERTFGV   WIUYEFV", categories: ["aaaa", "bbbbb", "ccccc"], stock: 34, archived: false},
  {id: '1267896789678933', name: "Potion #16", price: 12.59, description: "awdwuiefgWIUERFG   IUWERTFGV   WIUYEFV", categories: ["aaaa", "bbbbb", "ccccc"], stock: 34, archived: false},
  {id: '128479033', name: "Potion #16", price: 12.59, description: "awdwuiefgWIUERFG   IUWERTFGV   WIUYEFV", categories: ["aaaa", "bbbbb", "ccccc"], stock: 34, archived: false},
  {id: '126983433', name: "Potion #16", price: 12.59, description: "awdwuiefgWIUERFG   IUWERTFGV   WIUYEFV", categories: ["aaaa", "bbbbb", "ccccc"],  stock: 34, archived: false},
  {id: '1205780433', name: "Potion #16", price: 12.59, description: "awdwuiefgWIUERFG   IUWERTFGV   WIUYEFV", categories: ["aaaa", "bbbbb", "ccccc"],stock: 34, archived: true},
  {id: '12308465793', name: "Potion #16", price: 12.59, description: "awdwuiefgWIUERFG   IUWERTFGV   WIUYEFV", categories: ["aaaa", "bbbbb", "ccccc"],  stock: 34, archived: false},
  {id: '1239568963', name: "Potion #16", price: 12.59, description: "awdwuiefgWIUERFG   IUWERTFGV   WIUYEFV", categories: ["aaaa", "bbbbb", "ccccc"],  stock: 34, archived: false},
]