export enum OrderStatus {
  NEW = 'NEW',
  PAID = 'PAID',
  REJECTED = 'REJECTED',
  PREPARING = 'PREPARING',
  PREPARED = 'PREPARED',
  SENT = 'SENT',
  IN_DELIVERY = 'IN_DELIVERY',
  DELIVERED = 'DELIVERED',
  IN_RETURN = 'IN_RETURN',
  RETURNED = 'RETURNED',
}
